version: 2
updates:
  # Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore patch updates for non-critical packages
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"

# Configuration options
registries:
  python-index:
    type: python-index
    url: https://pypi.org/simple/

# General settings
commit-message:
  prefix: "deps"
  include: "scope"
