services:
  flask_app:
    build: .
    container_name: frontend
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Persist the database and other data.
    ports:
      - "5001:5001"
    restart: unless-stopped