services:
  db:
    # Using Debian-based image for better compatibility with PostgreSQL client tools
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD_ENCRYPTION: scram-sha-256
      POSTGRES_INITDB_WALDIR: /var/lib/postgresql/wal
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --wal-segsize=64
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ci-init-scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app_network

  ai_server:
    image: ai_server:test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - OWM_API_KEY=${OWM_API_KEY}
      - FLASK_ENV=testing
      - FLASK_APP=ai_server.py
      - FLASK_DEBUG=1
      - PORT=5002
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - CI_BUILD=true
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./ai_experiments/data:/app/ai_experiments/data
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    # Run the AI server with gunicorn
    command: gunicorn --bind 0.0.0.0:5002 --workers 2 --timeout 120 --graceful-timeout 60 ai_server:app
    networks:
      - app_network

  frontend:
    image: frontend:test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - OWM_API_KEY=${OWM_API_KEY}
      - FLASK_ENV=testing
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PORT=${PORT}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - AI_SERVER_URL=http://ai_server:5002
    volumes:
      - .:/build
      - /build/.venv
      - /build/__pycache__
      - ./logs:/build/logs
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
      ai_server:
        condition: service_started
    # Install minimal critical packages and run Flask
    command: >
      sh -c "pip install flask python-dotenv requests pandas numpy &&
             cd /build && python -m flask run --host=0.0.0.0 --port=${PORT} --debug"
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge 