services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - ./code-server-data:/home/coder/.local/share/code-server  # Persist user data
      - ./config:/home/coder/.config/code-server  # Persist configuration
      - /var/run/docker.sock:/var/run/docker.sock  # Enable Docker access
      - ./workspace:/home/coder/workspace  # Workspace files
      - ./projects:/home/coder/projects  # Workspace files

    environment:
      - TZ=UTC
      - AUTH=none  # Disable authentication (optional)
    user: "1000:1000"