services:
  flask_app:
    image: dawttu00/dawttu_private:frontend
    container_name: frontend
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "5001:5001"
    restart: unless-stopped