services:
  db:
    # Using Debian-based image for better compatibility with PostgreSQL client tools
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_PASSWORD_ENCRYPTION: scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app_network

  ai_server:
    image: ai_server:test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=testing
      - FLASK_APP=ci_ai_server.py
      - FLASK_DEBUG=1
      - PORT=5002
      - ALPHA_VANTAGE_API_KEY=test-key
      - CI_BUILD=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ci_ai_server.py:/app/ci_ai_server.py:ro
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    # Use direct Python command, no shell
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5002"]
    networks:
      - app_network

  frontend:
    image: frontend:test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=testing
      - FLASK_APP=app.py
      - PORT=${PORT}
      - ALPHA_VANTAGE_API_KEY=test-key
      - AI_SERVER_URL=http://ai_server:5002
    volumes:
      - ./app.py:/app/app.py:ro
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
      ai_server:
        condition: service_started
    # Use direct Python command, no shell and no package installation
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=${PORT}"]
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge 